Add API endpoint/webhook for Twilio to call when messages come in (#39)
* Add API endpoint/webhook for Twilio to call when messages come in

Implements: #3

* Add DI registrations

* Fix api controller

* fix because:
System.InvalidOperationException: The LINQ expression 'DbSet<Requester>()
2023-03-04T20:04:51.914521400Z           .Where(r => string.Equals(
2023-03-04T20:04:51.914527600Z               a: r.RequesterNumber,
2023-03-04T20:04:51.914530600Z               b: __phoneNumber_0,
2023-03-04T20:04:51.914534200Z               comparisonType: OrdinalIgnoreCase))' could not be translated. Additional information: Translation of the 'string.Equals' overload with a 'StringComparison' parameter is not supported.